# Generated by Django 2.2 on 2021-06-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.SmallIntegerField()),
                ('question', models.TextField()),
                ('correct_ans', models.TextField()),
                ('question_marks', models.SmallIntegerField()),
                ('question_type', models.TextField()),
                ('std_id', models.SmallIntegerField()),
                ('std_answer', models.SmallIntegerField()),
            ],
        ),
    ]
