# Generated by Django 2.2 on 2021-06-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.SmallIntegerField()),
                ('option', models.TextField()),
            ],
        ),
    ]
