# Generated by Django 2.2 on 2021-06-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_mcqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='std_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='std_id',
            field=models.SmallIntegerField(null=True),
        ),
    ]
