# Generated by Django 2.2 on 2021-06-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20210601_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='std_answer',
            field=models.TextField(null=True),
        ),
    ]
